/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yusuke' at '17/10/08 15:16' with Gradle 2.14.1
 *
 * @author yusuke, @date 17/10/08 15:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
